-- Flyway tracks what has run in its own schema history table, so a migration is
-- applied exactly once and never has to be written to survive re-running.
-- Never edit a migration that has already run anywhere: add V2__... instead.
--
-- Replace the example table with your own schema.

-- Oracle has no IF NOT EXISTS; Flyway's history table is what makes this safe.
CREATE TABLE items (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX items_created_at_idx ON items (created_at DESC);
